# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics

on:
  schedule:
    - cron: "0 4,14 * * *" # runs every day at 9 AM and 7 PM PKT
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: shhahhussain
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Karachi

          # Show private contributions (requires properly scoped PAT)
          config_gists: yes
          config_display: large

          # Optional plugin settings
          plugin_followup: no
          plugin_followup_sections: repositories
          plugin_lines: no

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_habits_charts_type: classic
          plugin_habits_days: 100
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: repositories_batch

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: css, scss, html, php
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # Contributor plugin to show public + private contributions
          plugin_contributors: yes
          plugin_contributors_contributions: yes
